name: Bob the Builder

# Run on push to any branch, except dev which is reserved for future
# Coverity Scan runs (limited number of tokesn /24h).  Also run on any
# pull request to check against regressions.
on:
  push:
    branches:
      - '*'
      - '!dev'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y tree
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make -j3
      - name: Install to ~/tmp and Inspect
        run: |
          make install DESTDIR=~/tmp prefix=/usr/local
          tree ~/tmp
      - name: Unit Tests
        run: |
          make check
